### ISSUE TITLE
update to Luna 4.4.2 causes Aptana to prevent Eclipse from loading because of org.eclipse.jface.text errors

### ISSUE THREAD

**Issue by allenatdecisiv** [aptana/studio3#301]
It seems an update in Eclipse 4.4.2 has caused Aptana to prevent the Eclipse Workbench from loading successfully. I have a very large (10K+ lines) log file with Aptana unresolvable errors. They are all similar to this:
```
!SESSION 2015-03-21 03:41:05.940 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY com.aptana.build.ui 4 0 2015-03-21 03:41:07.148
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.aptana.build.ui [25]
  Unresolved requirement: Require-Bundle: com.aptana.ui
    -> Bundle-SymbolicName: com.aptana.ui; bundle-version="3.1.4.1425082404"; singleton:="true"
       com.aptana.ui [2260]
         Unresolved requirement: Require-Bundle: org.eclipse.jface.text; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY com.aptana.console 4 0 2015-03-21 03:41:07.153
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.aptana.console [29]
  Unresolved requirement: Require-Bundle: org.eclipse.jface.text

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY com.aptana.debug.ui 4 0 2015-03-21 03:41:07.156
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.aptana.debug.ui [35]
  Unresolved requirement: Require-Bundle: org.eclipse.debug.ui; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.debug.ui; bundle-version="3.10.2.v20141014-1039"; singleton:="true"
       org.eclipse.debug.ui [1998]
         Unresolved requirement: Require-Bundle: org.eclipse.ui.console; bundle-version="[3.5.300,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.ui.console; bundle-version="3.5.300.v20140424-1437"; singleton:="true"
              org.eclipse.ui.console [815]
                Unresolved requirement: Require-Bundle: org.eclipse.jface.text; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

The version of org.eclipse.jface.text that I have in my Eclipse 4.4.2 plugins folder is:
org.eclipse.jface.text_3.9.2.v20141003-1326.jar

If I download the org.eclipse.jface.text from Eclipse 4.4.1 and install it to the plugins folder, Eclipse Workbench loads:
org.eclipse.jface.text_3.9.1.v20140827-1810.jar
org.eclipse.jface.text_3.9.2.v20141003-1326.jar

**Comment by allenatdecisiv** [comment]
version of Aptana I am using:
3.7.0.201503171652-7g7837jBWempPRYN5WtJ6sf2nPqT
