### ISSUE TITLE
Web preview does not work in Aptana plugin for Eclipse Luna

### ISSUE THREAD

**Issue by dezord** [aptana/studio3#321]
**The Issue**
If Aptana studio is installed as a plugin to Eclipse Luna, then the web preview does not work and gives the following error:
>Testing WebServer connection failed
Connection refused: connect

A look into the terminal output gives some more revealing information:
```java
Exception in thread "Thread-18" java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.nio.protocol.HttpAsyncService.<init>(Lorg/apache/http/protocol/HttpProcessor;Lorg/apache/http/ConnectionReuseStrategy;Lorg/apache/http/nio/protocol/HttpAsyncRequestHandlerResolver;Lorg/apache/http/params/HttpParams;)V" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, com/aptana/webserver/internal/core/builtin/LocalWebServer, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, org/apache/http/nio/protocol/HttpAsyncService, have different Class objects for the type org/apache/http/params/HttpParams used in the signature
        at com.aptana.webserver.internal.core.builtin.LocalWebServer.runServer(LocalWebServer.java:195)
        at com.aptana.webserver.internal.core.builtin.LocalWebServer.access$0(LocalWebServer.java:176)
        at com.aptana.webserver.internal.core.builtin.LocalWebServer$1.run(LocalWebServer.java:149)
```

Web preview works fine in standalone Aptana studio.
This problem has has been reported already at least twice before on StackOverflow ([here](http://stackoverflow.com/questions/25223563/cant-establish-a-connection-to-the-server-at-127-0-0-18020-aptana-studio-3) and [here](http://stackoverflow.com/questions/25627686/aptana-eclipse-plug-in-run-in-firefox-testing-webserver-connection-failed)).

**Steps to reproduce**
Simply go into an Aptana web project in Eclipse Lune with the Aptana Studio plugin installed and press the green Run button.

**Comment by mingchan** [comment]
@dezord - Did you resolve the issue? I just upgraded from juniper to mars and start seeing the same issue.

**Comment by dezord** [comment]
No I did not. At that point I just decided to install Aptana Studio standalone

**Comment by JirkaDellOro** [comment]
Same problem here with mars.

**Comment by rcale** [comment]
I resolved this issue by doing the following: 
BEFORE running the web preview (green button) from Eclipse, open an independent instance of Firefox browser. You should see a request for accepting an Aptana Studio plugin. Accept it, then close Firefox. Then go back and click the green "Run" button in Eclipse.
It seems that the missing Firefox plugin was the problem.
