### ISSUE TITLE
Installation fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by quinze26** [aptana/studio3#523]
I've installed Java 11, Git libraries and Aptana on Ubuntu 20.04. It runs up to the point where you enter the workspace directory, then crashes with numerous eclipse errors in the metadata log file.  For example:
!ENTRY org.eclipse.osgi 4 0 2020-05-14 20:08:37.125
!MESSAGE Application error
!STACK 1
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491) and many more
Full file attached:
[log.txt](https://github.com/aptana/studio3/files/4630441/log.txt)

What have I failed to do?

**Comment by Sanosuke94** [comment]
Hello. I believe Aptana only works on java version 8

**Comment by quinze26** [comment]
Thank you. Yes, I found out elsewhere that Aptana needs an earlier version of Java. I installed Java 8 and all works well.
